---
# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.20"
  amd64: "ghcr.io/home-assistant/amd64-base:3.20"
  armhf: "ghcr.io/home-assistant/armhf-base:3.20"
  armv7: "ghcr.io/home-assistant/armv7-base:3.20"
  i386: "ghcr.io/home-assistant/i386-base:3.20"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Blocky"
  org.opencontainers.image.description: "Fast and lightweight DNS proxy as ad-blocker for local network with many features."
  org.opencontainers.image.source: "https://github.com/chafi-cassim/hassio-addon-blocky"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
